import {
  ArrowDownLeft,
  Boxes,
  Braces,
  Database,
  GitBranch,
  Layers,
  Link2,
  ListTree,
  MousePointer2,
  Network,
  PanelsTopLeft,
  Search,
  Settings2,
  Shapes,
  ShieldCheck,
} from 'lucide-react';
import type { LessonIcon } from '../learning/types.ts';
export const lessonIcons = {
  write: ArrowDownLeft,
  search: Search,
  network: Network,
  shield: ShieldCheck,
  layers: Layers,
  boxes: Boxes,
  settings: Settings2,
  branch: GitBranch,
  document: Braces,
  shapes: Shapes,
  embed: PanelsTopLeft,
  reference: Link2,
  pointer: MousePointer2,
  index: ListTree,
} satisfies Record<LessonIcon, typeof Database>;
